# -*- coding: utf-8 -*-
"""Teste.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ls4ePk4B8yvk2cexXsH1aNO_9zu5y_VN
"""

import requests

def get_params():
  line = input(("Informe os operadores "))
  line = line.split(" ")
  if len(line) ==0:
    dados = {}
  elif len(line)==1:
    dados = {"x":line[0]}
  elif len(line)==2:
    dados = {"x":line[0],"y":line[1]}
  else:
    raise Exception("Numero de operadores inválido")
  return dados

def requisicao(url,data):
  response = requests.post(url, json=data)
  print()
  print(response.text)

def menu():
  print("1-ADIÇÃO --- X+Y")
  print("2-SUBTRAÇÃO --- X-Y")
  print("3-MULTIPLICAÇÃO --- X*Y")
  print("4-DIVISÃO --- X/Y")
  print("5-EXPONENCIAL --- X^Y")
  print("6-POTENCIAÇÃO --- X**Y")
  print("7-LOG --- LOG(X) OU LOGx Y e.g aceita 1 ou 2 parametros")
  print("8-SEN X")
  print("9-COSSENO X")
  print("10-TANGENTE X")
  print("11-ARC SENO X")
  print("12-ARC COSSENO X")
  print("13-ARC TANGENTE X")
  print("14-SENO HIPERBOLICO X")
  print("15-COSSENO HIPERBOLICO X")
  print("16-TANGENTE HIPERBOLICA X")
  print("17-ARC SENO HIPERBOLICO X")
  print("18-ARC COSSENO HIPERBOLICO X")
  print("19-ARC TANGENTE HIPERBOLICA X")




while True:
  print("1 - Realizar operação")
  print("2 - Exit")
  case = int(input("Opcao "))
  if case == 1:
    print("#MENU CALCULADORA")
    menu()
    case = int(input("Digite a operacao "))
    if case == 1: 
      dados = get_params()
      retorno = requisicao("http://localhost:5000/add", dados)
    elif case ==2:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/subtract", dados)
    elif case ==3:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/multiply", dados)
    elif case ==4:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/divide", dados)
    elif case ==5:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/exponential", dados)
    elif case ==6:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/pow", dados)
    elif case ==7:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/log", dados)
    elif case ==8:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/seno", dados)
    elif case ==9:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/cosseno", dados)
    elif case ==10:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/tan", dados)
    elif case ==11:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/aseno", dados)
    elif case ==12:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/acosseno", dados)
    elif case ==13:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/atan", dados)
    elif case ==14:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/senoh", dados)
    elif case ==15:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/cossenoh", dados)
    elif case ==16:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/tanh", dados)
    elif case ==17:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/asenoh", dados)
    elif case ==18:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/acossenoh", dados)
    elif case ==19:
      dados = get_params()
      retorno = requisicao("http://localhost:5000/atanh", dados)


  elif case == 2:
    print("BYEEE")
    break

#x = 1.0
#if x>0.99 or x< -0.99:
#  res = "Arco Tangente hiperbólico só está definido para [-0.99,0.99]"
#else:
#  ret = math.atanh(x)
